project_id = "jkctleefoomwpaglrvie"

[functions.verify-admin-password]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.ai-property-search]
verify_jwt = false
