// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkctleefoomwpaglrvie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprY3RsZWVmb29td3BhZ2xydmllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Nzg5NjAsImV4cCI6MjA2OTA1NDk2MH0.QGzHZYiP-m_ayMQ5RjYBLbSRd2J400E4c-UjHNvhmHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});